import Navbar from "../components/Navbar.jsx";
import "./Logs.css";
import Log from "../components/Log.jsx";

function Logs() {
  return (
    <>
      <Navbar />
      <div className="logsText">
        <div className="logsinfo">
        <h1 class="logs-h1">
          <span>LOGS</span>
        </h1>
        <p class="logs-p">
          This log page provides a comprehensive list of all alerts generated by
          the Women Safety Analytics system, tracking potential threats in
          real-time. Each entry includes details such as the time, location,
          type of alert, and current status for efficient monitoring and
          response.
        </p>
        </div>
      </div>

      <div className="logData">
        <Log address="KJ Somaiya College of Enginnering" />{" "}
        {/*Add js after backend of logs is done to get the details using the map*/}
      </div>
    </>
  );
}

export default Logs;
